name: agrow
description: "A Flutter app for farmers."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  image_picker: ^1.0.7       # For crop disease image upload
  flutter_localizations:     # For multilingual support
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  # Uncomment and add assets if you have images:
  # assets:
  #   - assets/logo.png
  #   - assets/image1.png